name: ci
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  static-site:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Build static assets
        working-directory: client
        run: |
          bun install --frozen-lockfile
          bun test
          bun run build:page

      - name: Upload static assets
        uses: actions/upload-artifact@v4
        with:
          path: client/dist

      - name: Deploy static assets
        uses: guardian/actions-static-site@v3
        with:
          app: cql-sandbox
          domain: cql-sandbox.gutools.co.uk
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  gu-cdk-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@96cf3f09dc501acdad7807fffe97dba9fa0709be # v1.1.5

      - name: Run tests and build JAR
        run: sbt test assembly

      - name: Generate CDK
        working-directory: ./cdk
        run: |
          npm ci
          npm test
          npm run synth

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: cql::cql-lambda
          configPath: ./cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - ./cdk/cdk.out/CqlLambda-PROD.template.json
            cql-lambda:
              - ./target/scala-3.4.2/cql-lambda.jar
