name: ci
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  static-site:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Build static assets
        working-directory: prosemirror-client
        run:
          bun build

      - name: Upload static assets
        uses: actions/upload-artifact@v3
        with:
          path: dist

      - name: Deploy static assets
        uses: guardian/actions-static-site@v2
        with:
          app: cql
          domain: cql.gutools.co.uk
          guActionsRiffRaffRoleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

  gu-cdk-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'sbt'

      - name: Run tests and build JAR
        run: sbt test assembly

      - name: Generate CDK
        working-directory: ./cdk
        run: |
          npm ci
          npm test
          npm run synth

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: cql::cql-lambda
          configPath: ./cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - ./cdk/cdk.out/CqlLambda-PROD.template.json
            cql-lambda:
              - ./target/scala-3.3.1/cql-lambda.jar
